CREATE TABLE USER (ID INT NOT NULL, NAME VARCHAR(20), BIRTH_DATE VARCHAR(10), UNIQUE KEY (ID));
CREATE TABLE TRANSACTION (ID INT NOT NULL, TYPE VARCHAR(6), CODE VARCHAR(2), BRANCH_ID INT, USER_ID INT, UNIQUE KEY (ID), FOREIGN KEY (USER_ID) REFERENCES USER(ID) );
CREATE TABLE BRANCH (ID INT NOT NULL, ADDRESS VARCHAR(100), UNIQUE KEY(ID));
CREATE TABLE SECURITIES_FOR_BRANCH (BRANCH_ID INT NOT NULL, SEC_ID INT NOT NULL, DATE VARCHAR(10), ACCESS VARCHAR(6));
CREATE TABLE LOT (ID INT NOT NULL, TRAN_ID INT, SEC_ID INT, DATE VARCHAR(10), PRICE DOUBLE, AMOUNT INT, UNIQUE KEY(ID), FOREIGN KEY(TRAN_ID) REFERENCES TRANSACTION(ID));
CREATE TABLE SECURITY (ID INT NOT NULL, DESC VARCHAR(100));